services:
  redis:
    image: redis:8.6.2-alpine3.23
    container_name: c-redis
    environment:
      - REDIS_PASSWORD=default
    ports:
      - 6379:6379
    networks:
      - converter-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "default", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 1s

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: c/postgres:16.13-alpine3.22
    container_name: c-postgres
    user: 1000:1000
    environment:
      POSTGRES_DB: converter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      LANG: ru_RU.UTF-8
    ports:
      - 65432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - converter-network
    restart: on-failure:3
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d converter'"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  backend:
    image: c/backend
    container_name: c-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/src:/src
    ports:
      - 8000:8000
    networks:
      - converter-network
    depends_on:
      postgres:
        condition: service_healthy
        restart: false
      redis:
        condition: service_healthy
        restart: false
    user: 1000:1000
    environment:
      JWT_SECRET_KEY: your-super-secret-jwt-key-min-32-chars-long
      JWT_ACCESS_CSRF_COOKIE_NAME: csrf_access_token
      JWT_REFRESH_CSRF_COOKIE_NAME: csrf_refresh_token
      JWT_ACCESS_COOKIE_NAME: access_token
      JWT_REFRESH_COOKIE_NAME: refresh_token
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 3
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: 30
      DATABASE_URL: postgresql://user:password@postgres:5432/converter
      REDIS_URL: redis://default:default@redis:6379/0
      CORS_ORIGINS: "[\"*\"]"
      SALT_ROUNDS: 18
      BACKEND_DOMAIN: converter.me
      FRONTEND_URL: https://converter.me
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  frontend:
    image: c/frontend
    container_name: c-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/:/src
    ports:
      - 5173:5173
    networks:
      - converter-network
    depends_on:
      - backend
    environment:
      VITE_API_URL: https://converter.me
    restart: on-failure:5

  nginx:
    image: nginx:stable
    container_name: c-nginx
    environment:
      TZ: Europe/Moscow
    volumes:
      - nginx_sources:/etc/nginx/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - converter-network
    depends_on:
      - backend
      - frontend
    restart: on-failure:3

volumes:
  nginx_sources:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/pg_data

networks:
  converter-network:
    name: converter-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/24
